myapp/urls.py
from django.urls import path
from . import views
# je viens d'ajouter
from django.contrib.auth import views as auth_views
from .views import  AjaxView

urlpatterns = [
    path('', views.index, name ='index'),
    path('register/', views.register, name ='register'),   
    path('login/', views.login, name ='login'),
    path('port_etu.html/', views.portEtu, name ='portEtu.html'),
    path('portAdmin/', views.portAdmin, name ='portAdmin'),
    path('portAdmin/gestion_candidatures/', views.gestion_candidatures, name ='gestion_candidatures'),
    path('portAdmin/gestion_inscriptions/', views.gestion_inscriptions, name ='gestion_inscriptions'),
    path('genie_informatique/', views.genie_informatique, name ='genie_informatique'),
    path('genie_civil/', views.genie_civil, name ='genie_civil'),
    path('genie_Industriel&Logistique/', views.genie_Industriel_Logistique, name ='genie_Industriel&Logistique'),
    path('management/', views.management, name ='management'),
    path('portAdmin/valider_annee/', views.valider_annee, name ='valider_annee'),
    path('portAdmin/gestion_notes/', views.gestion_notes, name ='gestion_notes'),
    path('ajax/etudiants/', AjaxView.as_view(), name='ajax_etudiants'),
    path('portAdmin/gestion_emploi_du_temps/', views.gestion_emploi_du_temps, name ='gestion_emploi_du_temps'),
    path('reinitialiser_emploi/<int:filiere_id>/<int:annee_id>/', views.reinitialiser_emploi, name='reinitialiser_emploi'),
    path('portAdmin/gestion_absences/', views.gestion_absences, name ='gestion_absences'),
    path('portAdmin/consulter_emploi/', views.consulter_emploi, name ='consulter_emploi'),
    path('portAdmin/consulterNotes.html/', views.consulter_notes, name ='consulterNotes.html'),
    path('portAdmin/consulter_absences/', views.consulter_absences, name ='consulter_absences'),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('myapp.urls'))
    
]

myapp/forms.py
from django import forms
from .models import Note, Filiere, Annee, Candidat, Matiere,Emploi,Etudiant,Absence


class NoteForm(forms.ModelForm):
    filiere = forms.ModelChoiceField(queryset=Filiere.objects.all())
    annee_scolaire = forms.ModelChoiceField(queryset=Annee.objects.all())
    etudiant = forms.ModelChoiceField(queryset=Etudiant.objects.none())
    matiere = forms.ModelChoiceField(queryset=Matiere.objects.all())
    note_semestre1 = forms.DecimalField()
    note_semestre2 = forms.DecimalField()

    class Meta:
        model = Note
        fields = ['filiere', 'annee_scolaire', 'etudiant', 'matiere', 'note_semestre1', 'note_semestre2']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        if 'filiere' in self.data:
            try:
                filiere_id = int(self.data.get('filiere'))
                annee_id = int(self.data.get('annee'))
                self.fields['etudiant'].queryset = Etudiant.objects.filter(filiere_id=filiere_id, annee_id=annee_id)
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['etudiant'].queryset = self.instance.filiere.Etudiant.filter(annee_id=self.instance.annee_id)

    def __str__(self):
        return self.filiere

        

class EmploiForm(forms.ModelForm):
    filiere = forms.ModelChoiceField(queryset=Filiere.objects.all(), required=True)
    annee = forms.ModelChoiceField(queryset=Annee.objects.all(), required=True)
    jour = forms.ChoiceField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], required=True)
    heures = forms.ChoiceField(choices=[('08h00-10h00', '08h00-10h00'), ('10h00-12h00', '10h00-12h00'), ('14h00-16h00', '14h00-16h00'), ('16h00-18h00', '16h00-18h00')], required=True)
    matiere = forms.ModelChoiceField(queryset=Matiere.objects.all(), required=True)

    class Meta:
        model = Emploi
        fields = ('filiere', 'annee', 'jour', 'heures', 'matiere')

    def __init__(self, *args, **kwargs):
        super(EmploiForm, self).__init__(*args, **kwargs)
        self.fields['jour'].label = 'Jour'
        self.fields['heures'].label = 'Heures'
        self.fields['matiere'].label = 'Matière'
        


class ConsulterEmploiForm(forms.Form):
    filiere = forms.ModelChoiceField(queryset=Filiere.objects.all())
    annee = forms.ModelChoiceField(queryset=Annee.objects.all())


class ConsulterNotesForm(forms.Form):
    filiere = forms.ModelChoiceField(
        queryset=Filiere.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='Filière'
    )
    annee = forms.ModelChoiceField(
        queryset=Annee.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='Année'
    )
    etudiant = forms.ModelChoiceField(
        queryset=Etudiant.objects.none(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='Étudiant'
    )



class ConsulterEmploiForm(forms.Form):
    filiere = forms.ModelChoiceField(queryset=Filiere.objects.all())
    annee = forms.ModelChoiceField(queryset=Annee.objects.all())


class ConsulterAbsencesForm(forms.Form):
    filiere = forms.ModelChoiceField(
        queryset=Filiere.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='Filière'
    )
    annee = forms.ModelChoiceField(
        queryset=Annee.objects.all(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='Année'
    )
    etudiant = forms.ModelChoiceField(
        queryset=Etudiant.objects.none(),
        widget=forms.Select(attrs={'class': 'form-control'}),
        label='Étudiant'
    )


class AbsencesForm(forms.ModelForm):
    filiere = forms.ModelChoiceField(queryset=Filiere.objects.all(), required=True)
    annee = forms.ModelChoiceField(queryset=Annee.objects.all(), required=True)
    etudiant = forms.ModelChoiceField(queryset=Etudiant.objects.none())
    jour = forms.ChoiceField(choices=[('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], required=True)
    heures = forms.ChoiceField(choices=[('08h00-10h00', '08h00-10h00'), ('10h00-12h00', '10h00-12h00'), ('14h00-16h00', '14h00-16h00'), ('16h00-18h00', '16h00-18h00')], required=True)
    Absence = forms.IntegerField(max_value=1)

    class Meta:
        model = Absence
        fields = ('filiere', 'annee','etudiant', 'jour','heures', 'Absence')

    def __init__(self, *args, **kwargs):
        super(AbsencesForm, self).__init__(*args, **kwargs)
        self.fields['jour'].label = 'Jour'
        self.fields['heures'].label = 'Heures'
        self.fields['Absence'].label = 'Absence'


        if 'filiere' in self.data:
            try:
                filiere_id = int(self.data.get('filiere'))
                annee_id = int(self.data.get('annee'))
                self.fields['etudiant'].queryset = Etudiant.objects.filter(filiere_id=filiere_id, annee_id=annee_id)
            except (ValueError, TypeError):
                pass
        elif self.instance.pk:
            self.fields['etudiant'].queryset = self.instance.filiere.Etudiant.filter(annee_id=self.instance.annee_id)

class ValiderAnneeForm(forms.Form):
    filiere = forms.ModelChoiceField(queryset=Filiere.objects.all())
    annee = forms.ModelChoiceField(queryset=Annee.objects.all())

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['filiere'].widget.attrs.update({'class': 'form-control'})
        self.fields['annee'].widget.attrs.update({'class': 'form-control'})

       
        

templates/base.html
<!DOCTYPE html>
<html>
<head>
    <title>HestimAdministration</title>
    <!-- Add CSS, JS, and other common elements here -->
</head>
<body>
    <header>
        <!-- Add header content here -->
    </header>
    <nav>
        <!-- Add navigation menu here -->
    </nav>
    <main>
        {% block content %}
        <!-- Content from inherited templates will be rendered here -->
        {% endblock %}
    </main>
    <footer>
        <!-- Add footer content here -->
    </footer>
</body>
</html>

templates/consulterEmploi.html
<h1>Consulter l'emploi du temps</h1>

<form method="post" action="consulter_emploi">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Consulter</button>
</form>

{% if emploi %}
    <h2>Emploi du temps de la classe {{ form.cleaned_data.filiere }} - {{ form.cleaned_data.annee }}</h2>
    <table>
        <thead>
            <tr>
                <th>Jour</th>
                <th>Heures</th>
                <th>Matière</th>
            </tr>
        </thead>
        <tbody>
            {% for e in emploi %}
                <tr>
                    <td>{{ e.jour }}</td>
                    <td>{{ e.heures }}</td>
                    <td>{{ e.matiere }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endif %}

templates/consulterNotes.html
    <h1>Consultez les de notes de:</h1>
<form method="post" action="{% url 'consulterNotes.html'%}">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Consulter</button>
  </form>
  
  {% if notes %}
    <h2>Notes de {{ form.cleaned_data.etudiant }}:</h2>
    <table>
      <thead>
        <tr>
          <th>Matière</th>
          <th>Note</th>
        </tr>
      </thead>
      <tbody>
        {% for note in notes %}
          <tr>
            <td>{{ note.matiere.nom }}</td>
            <td>{{ note.note }}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
  {% endif %}

templates/gestion_absences.html
{% extends 'base.html' %}

{% block content %}
  <h1>Ajouter les absences pour un etudiant donné</h1>
  <form method="post" action="gestion_absences">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit" class="btn btn-primary">Enregistrer</button>
  </form>

  {% if messages %}
    {% for message in messages %}
      <div class="alert alert-success">{{ message }}</div>
    {% endfor %}
  {% endif %}
{% endblock %}



<form method="post" class="form-inline my-2 my-lg-0">
    {% csrf_token %}
    <button class="btn btn-outline-danger my-2 my-sm-0" type="submit" formaction="{% url 'reinitialiser_absences' filiere_id=filiere.id annee_id=annee.id etudiant_id=etudiant.id %}">Réinitialiser Absences</button>
  </form>

templates/gestion_candidature.html
<h1>une liste des candidats s'affichera ici avec leurs statuts</h1>
{% for candidat in candidats %}
    <tr>
        <td>{{ candidat.username }}</td>
        <td>{{ candidat.date_naissance }}</td>
        <td>{{ candidat.email }}</td>
        <td>{{ candidat.telephone }}</td>
        <td>{{ candidat.nationalite }}</td>
        <td>{{ candidat.cycle_vise }}</td>
        <td>{{ candidat.niveau_etude }}</td>
        <td>{{ candidat.Anne_visee }}</td>
        <td>{{ candidat.filiere_visee }}</td>
        <td>{{ candidat.lettre_motivation }}</td>
        <td>{{ candidat.cv }}</td>
        <td>{{ candidat.bulletins }}</td>
        <td>{{ candidat.message }}</td>



        <td>
            {% if candidat.candidature_acceptee %}
                <span style="color: green;">Candidat Acceptée</span>
            {% else %}
                <span style="color:orange;">Candidat rejette ou en attente</span>
            {% endif %}
            <form method="POST" action="gestion_candidatures">
                {% csrf_token %}
                <input type="hidden" name="candidat_id" value="{{ candidat.id }}">
                <button type="submit" value="accepte" name="decision" style="background-color: green;">Accepter</button>
                <button type="submit" value="rejette" name="decidion" style="background-color: red;">Rejetter</button>
            </form>
        </td>
    </tr>
{% endfor %}

templates/gestion_inscription.html
<table>
  Tout ces candidats ont ete accepte! Veillez confirmer ou non leur inscription!
    <thead>
      <tr>
        <th>ID</th>
        <th>username</th>
        <th>Statut de l'inscription</th>
        <th>Marquer comme réussi</th>
      </tr>
    </thead>
    <tbody>
      {% for candidat_accepte  in candidats_acceptes  %}
      <tr>
        <td>{{candidat_accepte.id }}</td>
        <td>{{candidat_accepte.username }}</td>
        <td>
        <td>{% if candidat_accepte.inscription_reussi %}<span style="color: green;">Inscription Réussie</span> Réussie{% else %}<span style="color: orange;">Inscription attente</span>{% endif %}</td>
        <td>
          <form method="POST" action="gestion_inscriptions">
            {% csrf_token %}
            <input type="hidden" name="candidat_accepte_id" value="{{candidat_accepte.id }}">
            Deja inscrit?
            <input type="checkbox" name="inscription_reussi" value="OUI">
            <label for="inscription_reussi">OUI</label>
            <input type="checkbox" name="inscription_reussi" value="NON">
            <label for="inscription_EnAttente">NON</label>
            <button type="submit">Enregistrer</button>
          </form>
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>

templates/gestion_notes.html
<form method="post" action="{% url 'gestion_notes' %}">
    {% csrf_token %}
    {{ form.as_p }}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        // Lorsque la filière est changée
        $("#id_filiere").change(function () {
            var filiereId = $(this).val();
            var anneeScolaireId = $("#id_annee").val();
            var url = $("#noteForm").attr("data-etudiant-url") + "?filiere_id=" + filiereId + "&annee_scolaire_id=" + anneeScolaireId;

            $.ajax({
                url: url,
                success: function (data) {
                    // Met à jour la liste des étudiants
                    var etudiantSelect = $("#id_etudiant");
                    etudiantSelect.empty();
                    etudiantSelect.append('<option value="">---------</option>');
                    $.each(data, function(key, value) {
                        etudiantSelect.append('<option value="' + key + '">' + value + '</option>');
                    });
                }
            });
        });

        // Lorsque l'année scolaire est changée
        $("#id_annee").change(function () {
            var filiereId = $("#id_filiere").val();
            var anneeScolaireId = $(this).val();
            var url = $("#noteForm").attr("data-etudiant-url") + "?filiere_id=" + filiereId + "&annee_id=" + anneeScolaireId;

            $.ajax({
                url: url,
                success: function (data) {
                    // Met à jour la liste des étudiants
                    var etudiantSelect = $("#id_etudiant");
                    etudiantSelect.empty();
                    etudiantSelect.append('<option value="">---------</option>');
                    $.each(data, function(key, value) {
                        etudiantSelect.append('<option value="' + key + '">' + value + '</option>');
                    });
                }
            });
        });
    });
</script>
    <button type="submit" class="btn btn-primary">Enregistrer</button>
</form>

templates/login.html
<h1>Connectez vous maintenant</h1>

<style>
    h5{
        color: red;
    }
</style>


{% for message in messages %}
<h5> {{message}} </h5>
{% endfor %}

<form method="POST" action="{% url 'login' %}">
    {% csrf_token %}
    <input type="text" placeholder="username" name="username"class="form-control"><br>
    <input type="password" placeholder="password" name="password"class="form-control"><br>
    <input type="submit" value="submit" name="submit"class="form-control">
</form>